dependencies:
- name: api-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: exposecontroller
  version: 2.3.118
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.118
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: react-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.44
- name: strapi-cms
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
