PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: simonjamesrowe.com
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-simonjamesrowe-com-p
    tlsacme: "true"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
prow: {}
react-ui:
  apiUrl: https://api-jx-staging.simonjamesrowe.com
  gaTrackingToken: UA-179384022-3
  hotJarTrackingToken: 2022739
strapi-cms:
  databaseName: cms-staging